FROM node:20-alpine

RUN mkdir -p /nest
ADD . /nest

WORKDIR /nest

RUN npm -g i @nestjs/cli

RUN npm i

# Build production files
# RUN nest build shared
# RUN nest build database
# RUN nest build nest
RUN nest build api-sale

# Bundle app source
COPY . .

EXPOSE 3000
CMD ["node", "dist/apps/api-sale/main.js"]
