export const ENV_CONSTANT = {
    PORT: 'port',
    REMOTE_CONFIG_VERSION: 'remote_config.version',
    REMOTE_CONFIG_DATA: 'remote_config.row_data',
    CRM_USE_CORRELATION_MIDDLEWARE: 'crm.use_correlation_middleware',
    CRM_USE_METHOD_OVERRIDE_MIDDLEWARE: 'crm.use_method_override_middleware',
    CRM_USE_USER_CONTEXT_MIDDLEWARE: 'crm.use_user_context_middleware',
    CRM_USE_AUDIT_LOG_INTERCEPTOR: 'crm.use_audit_log_interceptor',
    CRM_USE_RESPONSE_INTERCEPTOR: 'crm.use_response_transform_interceptor',
    CRM_USE_HTTP_EXCEPTION_FILTER: 'crm.use_http_exception_filter',
    CRM_AUTH_GUARD_TYPE: 'crm.auth_guard_type',
    CRM_RESOURCE_GUARD_TYPE: 'crm.resource_guard_type',
    LOGGER_PROVIDER: 'logger.provider',
    LOGGER_TYPE: 'logger.type',
    LOGGER_LEVEL: 'logger.level',
    LOGGER_FORMAT: 'logger.format',
};