export const MESSAGE_ID = {
    LEAD_CREATE: 'LEAD_CREATE',
    LEAD_UPDATE: 'LEAD_UPDATE',
    LEAD_DELETE: 'LEAD_DELETE',
    TASK: 'TASK',
    ACCOUNT: 'ACCOUNT',
    CHECKIN: 'CHECKIN',
    DEAL: 'DEAL',
    DELIVERY: 'DELIVERY',
    QUOTE: 'QUOTE',
};