export const REQUEST_CONTEXT = 'REQUEST_CONTEXT';
export const USER_CONTEXT = 'USER_CONTEXT';
export const LOGGER = 'LOGGER';

export const CRM_SERVICE_OPTION = 'CRM_SERVICE_OPTION';
export const LOGGER_OPTION = 'LOGGER_OPTION';
export const SENTRY_OPTION = 'SENTRY_OPTION';
export const KEYCLOAK_OPTION = 'KEYCLOAK_OPTION';

export const LEAD_REPOSITORY = 'LEAD_REPOSITORY';